---
all:
  hosts:
    ciscolive-rtr-1.ciscolive.example:
      ansible_host: 198.18.1.195
      ansible_user: developer
      ansible_password: C1sco12345!CL

  vars:
    ntp_config:
      servers:
        - 172.16.1.254
        - 172.16.1.253

  children:
    xe_hosts:
      hosts:
        ciscolive-rtr-1.ciscolive.example:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
